Running 'unset PYTHONPATH && unset PYTHONHOME && unset PYTHONSTARTUP && export PYTHONNOUSERSITE=1 && . "/home/user/.config/Code - OSS/User/globalStorage/ackeeblockchain.tools-for-solidity/wake-conda/bin/activate" && wake lsp --port 40573'
[Error - 11:44:46 PM] Request workspace/executeCommand failed.
  Message: Traceback (most recent call last):
  File "/home/user/.config/Code - OSS/User/globalStorage/ackeeblockchain.tools-for-solidity/wake-conda/lib/python3.10/site-packages/wake/lsp/subprocess_runner.py", line 528, in run_printers_subprocess
    printer_name, callback = lsp_provider.get_callback(callback_id)
  File "/home/user/.config/Code - OSS/User/globalStorage/ackeeblockchain.tools-for-solidity/wake-conda/lib/python3.10/site-packages/wake/core/lsp_provider.py", line 186, in get_callback
    return self._callbacks[callback_id]
KeyError: 'callback_64889'

  Code: -32803 
